### PR TITLE
Refactor all css code to Styled Components

### PR DESCRIPTION
**Pull request by mmouradev**
Refactoring all the css code to Styled Components to facilitate maintenance and scalability

### CODE REVIEW

**Comment by rafaelmaiach** [comment]
@mmouradev check your IDE configuration please. You changed all single quotes to double quotes. This can lead to problems in the future and unnecessary changes.

**Comment by mmouradev** [comment]
> @mmouradev check your IDE configuration, please. You changed all single-quotes to double-quotes. This can lead to problems in the future and unnecessary changes. Also, checking the other files, the standard is for single-quotes on the repo.

Yes, I noticed this, I will change it in .editorconfig to be standard for everyone.

**Comment by Lorenalgm** [comment]
Thanks, Matheus! As soon as you finish refactoring, let me know, please

**Comment by mmouradev** [comment]
The refactor is finished!

**Pull request merged**
