### PR TITLE
feat(frontend): Ranking page

### PR DESCRIPTION
**Pull request by matheusdoedev**
## Description

Ranking page created.

## Checklist

- [x] page assets exported from Figma
- [x] page route ```/ranking```
- [x] page structure and style

## Issues

- #51

## Assets

Captura de tela de 2020-12-21 14-27-21

Captura de tela de 2020-12-21 14-27-39

Captura de tela de 2020-12-21 13-54-51

### CODE REVIEW

**Comment by Hilverton** [comment]
Dude, great job. I only make one suggestion in the responsive layout: from 375px downwards it would be interesting for the punctuation section to be under the section containing the user's name and position, that is, R. ListItem with flex-direction: column.

**Comment by matheusdoedev** [comment]
is it ? looks better, thanks for the suggestion :)

Captura de tela de 2020-12-21 15-49-48

**Comment by Hilverton** [comment]
It looks great

**Review by Hilverton — APPROVED** [review]

**Comment by Lorenalgm** [comment]
Thanks, Matheus! Great job :)

**Pull request merged**
