### PR TITLE
Add french translation to README

### PR DESCRIPTION
**Pull request by GuillaumeFalourd**
## What I did

- Translated the README into french.
- Added the french flag to` /translation/README.md` file.

References #36

### CODE REVIEW

**Comment by GuillaumeFalourd** [comment]
Let me know if I missed something @Lorenalgm & @esau-morais 👍

**Comment by GuillaumeFalourd** [comment]
On the #hacktoberfest page, I received this message about the repository:

```Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.```

I believe you should add it to encourage contributions 👍

**Comment by esau-morais** [comment]
> On the #hacktoberfest page, I received this message about the repository:
> 
> ```
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.
> ```
> 
> I believe you should add it to encourage contributions 👍

The repository and the issue need a topic and a label called `hacktoberfest` 

@pedrohram

**Review by esau-morais — APPROVED** [review]
Thank you for contribute with French language!!

_Note: You are following the required steps → Approved_

**Comment by pedrohram** [comment]
A recent merge caused a merge conflict.

Please resolve the conflict and we'll be merging right after.

Regards!

**Comment by GuillaumeFalourd** [comment]
Merge done @pedrohram 👍

**Pull request merged**
