### PR TITLE
Configure and add components tests

### PR DESCRIPTION
**Pull request by Lukazovic**
## Description:

This PR is related to issue #54 and aims to improve the quality of the project by ensuring everything is working as expected.

## How

- Fixed testing libraries to be devDependencies;
- Added a custom render to wrapper all the testing components with `GlobalStyles`, `react-router-dom` and `react-toastify` to re-use in all tests;
- Added `jest-styled-component` to be able to test styles and improve snapshots;
- Added Logo and Header tests to start. I'll add the other components tests in some other PR to not make it harder to understand.

## How to test

run:
```bash
yarn test
````

### CODE REVIEW

**Review by Isaac-alencar — APPROVED** [review]
### Reviwed and aproved

**Review by Isaac-alencar — CHANGES_REQUESTED** [review]
### Please, be sure that test files to be in ```__tests__``` directory. Following the pattern.
 - Suggestion: You can create a ```components``` folder in the ```__tests__``` directory

**Comment by Lukazovic** [comment]
> ### Please, be sure that test files to be in `__tests__` directory. Following the pattern.
> * Suggestion: You can create a `components` folder in the `__tests__` directory

@Isaac-alencar  I saw that pattern (tbh is not a pattern I like, I like to keep tests close to components) but the reason I haven't follow the pattern is because of the default configuration of the `test` script (`react-scripts test`). When you run `yarn test` it triggers this script but it does not find tests in the `__tests__` directory. It only finds the tests in the `__tests__` directory when I run `npx jest` but is not the best way to run tests in React.

I think we can update the current tests to follow a new pattern and ensure the `yarn test` will run all the tests. What do you think?

**Comment by ramos-ph** [comment]
Personally, I like the approach of decentralize the tests of a `__tests__` directory. It makes navigation easier, since the implementation file is on the same level of the test file.

**Comment by Isaac-alencar** [comment]
@Lukazovic I have to agree with you, this approach seems appropriate to project, although we don't have a lot of UI components, it can help us to achieve more organization on tests.

**Pull request merged**
